##
## EPITECH PROJECT, 2021
## teams
## File description:
## Makefile
##

all:	cstring string list

string:
	make -C string/ -s

cstring:
	make -C cstring/ -s

list:
	make -C list/ -s

clean:
	make clean -C string/ -s
	make clean -C cstring/ -s
	make clean -C list/ -s

fclean:
	make fclean -C string/ -s
	make fclean -C cstring/ -s
	make fclean -C list/ -s

re:
	make re -C string/ -s
	make re -C cstring/ -s
	make re -C list/ -s

.PHONY: all string cstring list clean fclean re